id: AC91D51B3
title: Toh_184-Teaching_the_Practice_of_a_Bodhisattva-v2
type: translation
pechas:
- ID8BC825B
- I4BFF6F1E
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-004
  eft-text-version: 1.0.10 2020
  title: Toh_184-Teaching_the_Practice_of_a_Bodhisattva-v2
alignment_to_base:
  ID8BC825B/1D07: A8D9
  I4BFF6F1E/1DE4: A8D9
